name = "giftcardlab"
compatibility_date = "2026-04-01"
pages_build_output_dir = "./public"

[[d1_databases]]
binding = "DB"
database_name = "perklt-stats"
database_id = "7784d27d-11be-47bf-99e0-52cb59d87c05"

[vars]
OGADS_URL = "https://checkmyapp.store/sl/o1ogr"
POSTBACK_SECRET = "797fcb0cb618ef8304d07c1551e569cb9bf407fcad6bf76d"
